### ISSUE TITLE
Add animation to show that file is added to the extension

### ISSUE THREAD

**Issue by filewallio** [filewallio/chrome-extension#1]
Add an animation that moves some file icon from the mouse pointer position of the "secure download" click to the position of the extension icon (or broadly the top right position ) to visually show that the download has been moved to the extension.

**Comment by cyberdock** [comment]
https://github.com/filewallio/chrome-extension/commit/339242915e021b1b6163821adbf4fcc571e28315

**Comment by TimothyBeene** [comment]
Hi Dirk, It's difficult to see what all was involved with this commit please see #9 I would like to base all changes on the dev branch for now.

Did you complete this feature or should I work on it still? If so what exactly did you have in mind for the animation I know I had what you describe implemented already (icon move from pointer to top right corner) but you mentioned you wanted it to look better. Do you have an example animation you like I can try to reproduce

**Comment by cyberdock** [comment]
The feature should work, and the animation is ok for now. 
However im not sure if the way i did the animation is ok or the "correct" way to do this. Could you check the indicator.js? I basically send message to popup.js and render the animation inside the current tab. I think the way i do it now requires the tab permission. On the other hand, we will need that permission anyway at some point to detect for example  specific websites and embedd  a new "secure download" button directly into the page.

**Comment by cyberdock** [comment]
I've ported the code to use indicator.js to dev
https://github.com/filewallio/chrome-extension/commit/79b9afde78e688a972716bd81f99c974f279253f  because is screwed the first commit. 
However i did not add this to webpack, so the package is broken now because of the changes in manifest.

**Comment by TimothyBeene** [comment]
Ok, I'll look at this, might be later this week though.
