### ISSUE TITLE
Open Extension Dialog on download start.

### ISSUE THREAD

**Issue by filewallio** [filewallio/chrome-extension#2]
After a user clicks "secure download", the extension should open its main window so the user can see the download been processed.

**Comment by TimothyBeene** [comment]
Unfortunately Chrome does not allow us to pragmatically open the popup little window.

Alternatively we could place a small progress bar on the filwallio icon and use `browserAction.setIcon()` method to change small progress bar.

Or we can place a badge on the filewallio icon indicating the download is starting.

**Comment by cyberdock** [comment]
Ah that too bad, but not that important, i think the download animation and the active download count indicator at the icon is enough.
