### ISSUE TITLE
Add download/processing counter to icon. 

### ISSUE THREAD

**Issue by filewallio** [filewallio/chrome-extension#3]
If a download/processing is active the icon should show the number of active processes in the icon. 
Aka the green firewallio extension icon with some small red circle bottom right that shows a number.

**Comment by cyberdock** [comment]
https://github.com/filewallio/chrome-extension/commit/3748e0213e111a82ff1225282e46bcb6c1cea61e

**Comment by TimothyBeene** [comment]
I have added this feature to the dev branch. I don't see a way to change the badge from a square to a circle and on firefox it shows to the top right. If this is important I can investigate further.

Badge on Chrome
![image](https://user-images.githubusercontent.com/16546441/75703899-fc31a200-5c7d-11ea-8751-4811ac1365e6.png)

Badge on Firefox
![image](https://user-images.githubusercontent.com/16546441/75703926-08b5fa80-5c7e-11ea-95e0-0e5bdd82d200.png)


577b35a

**Comment by cyberdock** [comment]
No position/form does not matter, we'll just use the default the browser provides
