### ISSUE TITLE
Firefox compatibility

### ISSUE THREAD

**Issue by filewallio** [filewallio/chrome-extension#5]
Can we do this so the same codebase is used for chrome and firefox? 
How is the best way to do this? rename this repo to "browser-extension" or do we need 2 repos ?

**Comment by TimothyBeene** [comment]
I think it is best to do this in one repo. I have already made a build script for making chrome and firefox builds (you can see on the Dev branch readme https://github.com/filewallio/chrome-extension/tree/dev)

**Comment by cyberdock** [comment]
nice!
