### ISSUE TITLE
Show login in popup if user is not logged in

### ISSUE THREAD

**Issue by cyberdock** [filewallio/chrome-extension#7]
I've added the html to popup.html (https://github.com/filewallio/chrome-extension/commit/7108dd3c8b39fe4e203ccb026f4630b6dd80c87d), but all js is still missing. 
About the "remember me" button:
 Can we test if chrome is logged in to a google account?
 If yes it would be nice if we store the password in the users storage and don't snow the "remember me" button.
 But if the user is not logged in into chrome, he might want to automatically logout off filewall.io on browser close. 
 Can this be done? If not, just remove "remember me" for now and always save password.

**Comment by TimothyBeene** [comment]
Ok, I put a login form in the popup like you asked check it out.
As for the chrome being logged into a google account I'll will need to look into that another day, I don't see an easy way to do that right now. So for now I have the "remember me" button but actually it always remembers you haha.

checkout the new version here 
https://github.com/filewallio/chrome-extension/releases/download/v0.0.4/filewallio-0.0.4.zip
