### ISSUE TITLE
Merge refactor into repo

### ISSUE THREAD

**Issue by TimothyBeene** [filewallio/chrome-extension#9]
I have pushed all the changes to the dev branch but I see you have already pushed some changes since I "branched" out.

As part of the refactor I added webpack which bundles some of the various .js files into one large file but it is not meant to be checked into the repo, only for the final package.

I would like to move the refactored code to the master branch and go ahead and re apply your changes to to the refactored code. Please let me know your thoughts.

**Comment by cyberdock** [comment]
Yep do as you like, i didn't get the whole webpack stuff, never used it and simply ignored it :)
I did not change much code, even if you undo/break what i did, i can simply redo that with some copypasta, so go for it

**Comment by TimothyBeene** [comment]
Great I overwrote most of your changes on the master branch.
